#!/bin/bash

echo "Criando diretórios..."

mkdir /publico
mkdir /adm
mkdir /ven
mkdir /sec

echo "Criando grupos de usuários..."

groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

echo "Criando usuários..."

useradd marina -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_ADM
useradd luiza -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_ADM
useradd jusefa -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_ADM

useradd ana -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_VEN
useradd filo -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_VEN
useradd renato -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_VEN

useradd maroca -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_SEC
useradd antunes -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_SEC
useradd robeval -m -s /bin/bash -p $(openssl passwd -crypt Senha1332) -G GRP_SEC

echo "Especificando permissões dos diretórios...."

chown root:GRP_ADM /adm
chown root:GRP_VEN /ven
chown root:GRP_SEC /sec

chmod 770 /adm
chmod 770 /ven
chmod 770 /sec
chmod 777 /publico

echo "Fim....."